name = "setlistconverter_backend"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat_v2" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

browser = { binding = "MYBROWSER", type = "browser" }
kv_namespaces = [
  { binding = "BROWSER_KV_DEMO", id = "be3255bc9432404185d2e666377f6d78" }
]
